# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MEZUKA BLOG
email: mezuka@mezuka.com
description: >
  This is a blog from Mezuka engineers. It was created in purpose of share development experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mezuka
github_username:  mezuka

# Build settings
markdown: kramdown
